# Generated by Django 5.2.1 on 2025-05-12 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ankesh', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chai',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
